CREATE TABLE IF NOT EXISTS SETTINGS  (
  ID               INT          NOT NULL AUTO_INCREMENT  PRIMARY KEY
  ,USER            VARCHAR(255) NOT NULL CONSTRAINT USER_NAME_UC UNIQUE
  ,PASSWORD        VARCHAR(50)
);